### ISSUE TITLE
[问题反馈]机械动力动力泵上面放置齿轮会多一个掉落物

### ISSUE THREAD

**Issue by YuHuoFei01** [creepebucket/creepe_ponder#6]
### 简述:  放置齿轮多爆一个

描述你怎么使用, 发生了什么？

执行在放置动力泵上面放置的齿轮时，齿轮放置成功，但是会错误产生一个齿轮掉落物。
如果不在动力泵上面放置，则一切正常。

### 复现步骤:
执行以下命令

pond = Ponder(5)
pond.block(20, (2, 1, 1), 'create:mechanical_pump')  # 动力泵
pond.block(40, (2, 2, 1), 'create:cogwheel')  # 齿轮

### 环境:

- creepe_ponder版本: 0.5.1f 最新
- python版本: 3.12
- MC版本:1.19.2

### 检查单:

**请复制此项, 并在对应项上打钩:**

- 我已经重复复现此bug多于 2 次 [ √  ]
- 我已经将问题模型简化到最小 [ √  ]
- 此问题在最新版本上仍旧存在 [  √ ]
- 我以及检查过没有重复内容 [ √  ]
![QQ图片20241011140052](https://github.com/user-attachments/assets/276e0eba-11b7-49ad-8768-cf7b92432c3a)

**Comment by MulatramAwA** [comment]
暂时理解为可能由于Mojang或者Create的神奇优化

**Comment by creepebucket** [comment]
#7 fixed
